"""Provider Abstraction Layer for EchoDrive.

The voice runtime interacts solely with these small abstract interfaces.
No provider-specific SDK details may leak into domain or voice runtime code.
"""

from abc import ABC, abstractmethod
from typing import AsyncGenerator, Dict, List, Optional, Any, Tuple


class ASRProvider(ABC):
    """Abstract interface for streaming Speech-to-Text."""

    @abstractmethod
    async def connect(self) -> None:
        """Initialize connection or websocket to ASR service."""
        pass

    @abstractmethod
    async def send_audio_chunk(self, pcm_bytes: bytes) -> None:
        """Send raw 16kHz 16-bit PCM audio frame to ASR."""
        pass

    @abstractmethod
    async def receive_transcripts(self) -> AsyncGenerator[Tuple[str, bool], None]:
        """Yield (text, is_final) as transcription results arrive."""
        yield ("", False)

    @abstractmethod
    async def close(self) -> None:
        """Gracefully close ASR connection."""
        pass


class LLMProvider(ABC):
    """Abstract interface for streaming Large Language Model completions."""

    @abstractmethod
    async def stream_chat(
        self,
        messages: List[Dict[str, str]],
        system_prompt: Optional[str] = None,
        generation_id: Optional[str] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream token deltas as they are generated by the model."""
        yield ""


class TTSProvider(ABC):
    """Abstract interface for streaming Text-to-Speech synthesis."""

    @abstractmethod
    async def synthesize_stream(
        self,
        text: str,
        generation_id: str,
        chunk_index: int = 0,
        is_final: bool = False,
    ) -> AsyncGenerator[bytes, None]:
        """Stream synthesized 16kHz 16-bit PCM audio chunks."""
        yield b""


class RTCGateway(ABC):
    """Abstract interface for realtime audio media plane (Agora RTC)."""

    @abstractmethod
    def generate_token(self, channel_name: str, uid: int, expire_seconds: int = 3600) -> str:
        """Generate official Agora RTC channel access token."""
        pass

    @abstractmethod
    async def join_channel(self, channel_name: str, uid: int) -> None:
        """Join Agora RTC media room."""
        pass

    @abstractmethod
    async def leave_channel(self, channel_name: str) -> None:
        """Leave Agora RTC media room."""
        pass

    @abstractmethod
    async def send_audio_frame(self, pcm_bytes: bytes) -> None:
        """Send PCM audio frame to Agora channel playback sink."""
        pass
